### ISSUE TITLE
Comments in `requirements.txt` file produce an error

### ISSUE THREAD

**Issue by IlyaMichlin** [repo-helper/hatch-requirements-txt#28]
If there is a comment in the `requirements.txt` file, the following error will be displayed: `packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)`

**Comment by domdfcoding** [comment]
Can you give the [comments](https://github.com/repo-helper/hatch-requirements-txt/tree/comments) branch a try?

You should be able to use the following in `pyproject.toml` to have that branch installed directly from GitHub when you build your project:

```toml
[build-system]
requires = ["hatch-requirements-txt@https://github.com/repo-helper/hatch-requirements-txt/archive/comments.zip"]
build-backend = "hatchling.build"
```

If it works for you I'll make a new release.
